services:
  postgresdb:
      image: postgres
      container_name: postgresdb
      env_file:
        - ./env/postgres.env
      volumes:
        - postgres_data:/var/lib/postgresql/data

  fastapi:
    build:
      context: .
      dockerfile: prod.dockerfile
    container_name: fastapi
    ports: 
      - '8000:8000'
    env_file:
      - ./env/backend.env
    depends_on:
      - postgresdb
volumes:
  postgres_data: